backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - label: "Gallery"
    name: "galleryImages"
    widget: "list"
    folder: "src/galleryData/images"
    create: true
    fields:
  - { label: Image, name: image, widget: image }
  - { label: Alternate Text, name: altText, widget: string }
  - {
      label: Image Type,
      name: type,
      widget: select,
      options: ["illustration", "ink"],
    }
